account:
  uin: 1233456
  password: ""
  encrypt: false
  status: 0
  relogin:
    delay: 3
    interval: 3
    max-times: 0
  use-sso-address: true
  allow-temp-session: false
  sign-servers:
    - url: http://127.0.0.1:9000
      key: 114514
      authorization: "-"
    - url: "-"
      key: 114514
      authorization: "-"
  rule-change-sign-server: 1
  max-check-count: 0
  sign-server-timeout: 60
  is-below-110: false
  auto-register: false
  auto-refresh-token: false
  refresh-interval: 40
  sign-server: http://127.0.0.1:9000
heartbeat:
  interval: 5
message:
  post-format: string
  ignore-invalid-cqcode: false
  force-fragment: false
  fix-url: false
  proxy-rewrite: ""
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false
  skip-mime-scan: false
  convert-webp-image: false
  http-timeout: 15
output:
  log-level: warn
  log-aging: 15
  log-force-new: true
  log-colorful: true
  debug: false
default-middlewares: &1
  access-token: ""
  filter: ""
  rate-limit:
    enabled: false
    frequency: 1
    bucket: 1
database:
  leveldb:
    enable: true
  sqlite3:
    enable: false
    cachettl: 3600000000000
servers:
  - ws:
      address: 0.0.0.0:9002
      middlewares:
        <<: *1